/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int NOT_NULL = 10;
  /** RegularExpression Id. */
  int NULL = 11;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 12;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 13;
  /** RegularExpression Id. */
  int REFERENCES = 14;
  /** RegularExpression Id. */
  int DROP_TABLE = 15;
  /** RegularExpression Id. */
  int DESC = 16;
  /** RegularExpression Id. */
  int SHOW_TABLES = 17;
  /** RegularExpression Id. */
  int SELECT = 18;
  /** RegularExpression Id. */
  int FROM = 19;
  /** RegularExpression Id. */
  int AS = 20;
  /** RegularExpression Id. */
  int WHERE = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int IS_NULL = 25;
  /** RegularExpression Id. */
  int IS_NOT_NULL = 26;
  /** RegularExpression Id. */
  int INSERT_INTO = 27;
  /** RegularExpression Id. */
  int VALUES = 28;
  /** RegularExpression Id. */
  int DELETE_FROM = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int LEFT_PAREN = 31;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int UNDERSCORE = 34;
  /** RegularExpression Id. */
  int SIGN = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int ALPHABET = 37;
  /** RegularExpression Id. */
  int ASTERISK = 38;
  /** RegularExpression Id. */
  int PERIOD = 39;
  /** RegularExpression Id. */
  int CHAR_STRING = 40;
  /** RegularExpression Id. */
  int INT_VALUE = 41;
  /** RegularExpression Id. */
  int DATE_VALUE = 42;
  /** RegularExpression Id. */
  int QUOTE = 43;
  /** RegularExpression Id. */
  int NON_QUOTE_CHAR = 44;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHAR = 45;
  /** RegularExpression Id. */
  int COMP_OP = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"not null\"",
    "\"null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\"drop table\"",
    "\"desc\"",
    "\"show tables\"",
    "\"select\"",
    "\"from\"",
    "\"as\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"is null\"",
    "\"is not null\"",
    "\"insert into\"",
    "\"values\"",
    "\"delete from\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<SIGN>",
    "<DIGIT>",
    "<ALPHABET>",
    "\"*\"",
    "\".\"",
    "<CHAR_STRING>",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "\"\\\'\"",
    "<NON_QUOTE_CHAR>",
    "<NON_QUOTE_SPECIAL_CHAR>",
    "<COMP_OP>",
  };

}
