/* Generated By:JavaCC: Do not edit this line. ScratchDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScratchDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int TABLE = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int PRIMARY = 13;
  /** RegularExpression Id. */
  int FOREIGN = 14;
  /** RegularExpression Id. */
  int KEY = 15;
  /** RegularExpression Id. */
  int REFERENCES = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int DESC = 18;
  /** RegularExpression Id. */
  int SHOW = 19;
  /** RegularExpression Id. */
  int TABLES = 20;
  /** RegularExpression Id. */
  int SELECT = 21;
  /** RegularExpression Id. */
  int FROM = 22;
  /** RegularExpression Id. */
  int AS = 23;
  /** RegularExpression Id. */
  int WHERE = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int IS = 27;
  /** RegularExpression Id. */
  int INSERT = 28;
  /** RegularExpression Id. */
  int INTO = 29;
  /** RegularExpression Id. */
  int VALUES = 30;
  /** RegularExpression Id. */
  int DELETE = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int PERIOD = 36;
  /** RegularExpression Id. */
  int UNDERSCORE = 37;
  /** RegularExpression Id. */
  int ASTERISK = 38;
  /** RegularExpression Id. */
  int SIGN = 39;
  /** RegularExpression Id. */
  int COMP_OP = 40;
  /** RegularExpression Id. */
  int LEGAL_IDENT = 41;
  /** RegularExpression Id. */
  int INT_VALUE = 42;
  /** RegularExpression Id. */
  int DATE_VALUE = 43;
  /** RegularExpression Id. */
  int CHAR_STRING = 44;
  /** RegularExpression Id. */
  int NON_QUOTE_CHAR = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int ALPHABET = 47;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHAR = 48;
  /** RegularExpression Id. */
  int QUOTE = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create\"",
    "\"table\"",
    "\"not\"",
    "\"null\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\"drop\"",
    "\"desc\"",
    "\"show\"",
    "\"tables\"",
    "\"select\"",
    "\"from\"",
    "\"as\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"is\"",
    "\"insert\"",
    "\"into\"",
    "\"values\"",
    "\"delete\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"_\"",
    "\"*\"",
    "<SIGN>",
    "<COMP_OP>",
    "<LEGAL_IDENT>",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<CHAR_STRING>",
    "<NON_QUOTE_CHAR>",
    "<DIGIT>",
    "<ALPHABET>",
    "<NON_QUOTE_SPECIAL_CHAR>",
    "\"\\\'\"",
  };

}
